server:
  port: 9000

delibird:
  database:
    url: ${DATABASE_URL:jdbc:h2:nio:./db/delibird_db;MODE=MySQL}
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:123456}
    driver: org.h2.Driver

spring:
  h2:
    console:
      enabled: true
  profiles:
    active: default
  flyway:
    url: ${delibird.database.url}
    user: ${delibird.database.user}
    password: ${delibird.database.password}
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:rabbitmqUser}
    password: ${RABBITMQ_PASSWORD:rabbitmqPass}
