server:
  port: 9000

delibird:
  database:
    url: jdbc:h2:mem:delibirddb;MODE=MySQL
    user: root
    password: 123456
    driver: org.h2.Driver

spring:
  datasource:
    url: ${delibird.database.url}
    username: ${delibird.database.user}
    password: ${delibird.database.password}
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: default
  flyway:
    url: ${delibird.database.url}
    user: ${delibird.database.user}
    password: ${delibird.database.password}
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
    virtual-host: "delibird"

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    shutdown:
      enabled: true
